### ISSUE TITLE
Custom prompt isn't persistent.

### ISSUE THREAD

**Issue by jedington** [Trace-Elements0/powershellforfun#7]
See below image.
![ScreenShot_20211009211357](https://user-images.githubusercontent.com/25874804/136678798-4322a6af-d20b-4ce3-98f7-b0f4807bb526.png)

Using either version of oh-my-posh doesn't change the results.

Need to figure out a way to make the prompt theme persistent:
- oh-my-posh v2.0.X uses .psm1 files for themes.
- oh-my-posh v3~5+ uses JSON files for themes.

**Comment by Trace-Elements0** [comment]
Not able to recreate this. I copy and pasted the custom profile we have in the repo into my own right now and it worked as expected. Going to keep looking into it

**Comment by jedington** [comment]
Problem identified: 
No current method in the install-dependencies.ps1 script or in the instructions on appending to: `$env:Path`

Solution 1: Permanently would append to $env:Path
```
###To add locations to the PSModulePath 
#Get the users current path value
$CurrentValue = [Environment]::GetEnvironmentVariable("Path", "User")    
#Add the new path             
[Environment]::SetEnvironmentVariable("Path", $CurrentValue + [System.IO.Path]::PathSeparator + "C:\Temp", "User")
#Inspect for new path
$Env:Path -Split ";"
```

Solution 2: Temporarily appends to `$env:Path` everytime the profile/PowerShell instance is started.
`$env:Path = "$env:HOMEDRIVE\Temp;$env:Path"`
